# .github/workflows/R-CMD-check.yml
name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.3' }
          - { os: macOS-latest,  r: '4.3' }
          - { os: windows-latest, r: '4.3' }

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: |
          install.packages("BiocManager")
          BiocManager::install()
          BiocManager::install("devtools")
          devtools::install_deps(dependencies = TRUE)

      - name: Check
        run: |
          devtools::check()
