# .github/workflows/R-CMD-check.yml
name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.3' }

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}


      - name: Install system dependencies
        run: |
          sudo apt install -y --no-install-recommends \
          libsodium-dev \
          libnetcdf-dev \
          libglpk-dev \
          curl \
          libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install()'
          Rscript -e 'BiocManager::install("devtools")'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      - name: Run devtools::check()
        run: |
          Rscript -e 'devtools::check()'
