# .github/workflows/test-coverage.yml
name: test-coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt install -y --no-install-recommends \
          libsodium-dev \
          libnetcdf-dev \
          libglpk-dev \
          curl \
          libcurl4-openssl-dev \
          ssh

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install(c("covr", "testthat"))'
          Rscript -e 'BiocManager::install()'

      - name: Run test coverage and upload to Codecov
        run: |
          Rscript -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
